### ISSUE TITLE
Saving sub-model returned from query of base doesn't work sometimes

### ISSUE THREAD

**Issue by amagee** [briankircho/mongoose-schema-extend#10] opened 2013-05-02 05:46 UTC
If I have model `Sub` whose schema extends the schema of a model `Base`, I can receive a `Sub` instance by calling `Base.findOne({}, ...)`, but when I try to `save` the instance I get this error:

```
/home/amagee/playfi/src/comet/node_modules/mongoose/lib/schema/documentarray.js:94
        doc.validate(function (err) {
            ^
TypeError: Object #<Object> has no method 'validate'
    at DocumentArray.doValidate (/home/amagee/playfi/src/comet/node_modules/mongoose/lib/schema/documentarray.js:94:13)
    at DocumentArray.doValidate (/home/amagee/playfi/src/comet/node_modules/mongoose/lib/schema/documentarray.js:102:9)
    at DocumentArray.SchemaType.doValidate (/home/amagee/playfi/src/comet/node_modules/mongoose/lib/schematype.js:569:22)
    at DocumentArray.doValidate (/home/amagee/playfi/src/comet/node_modules/mongoose/lib/schema/documentarray.js:73:35)
    at Document.validate.err (/home/amagee/playfi/src/comet/node_modules/mongoose/lib/document.js:922:9)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
```

Here's a short script demonstrating the problem.  The `items1` property works fine, and both work fine when I try to save an instance retrieved from `Sub.findOne`. But the `items2` property breaks when I try to save an instance retrieved from `Base.findOne`.

```javascript
var mongoose = require('mongoose/');
mongoose.connect("mongodb://localhost/test123db");
var extend = require('mongoose-schema-extend');
var Schema = mongoose.Schema;  

var BaseSchema = new Schema({
  name: String
}, { collection: "base", discriminatorKey: "type" });
var Base = mongoose.model('Base', BaseSchema); 

var SubSchema = BaseSchema.extend({
  items1: [String], // Fine
  items2: [{ key1: String, key2: String }] // Broken
});
var Sub = mongoose.model('Sub', SubSchema);

Base.remove(function() {
Sub.remove(function() {
  q = new Sub({ name: "Hello" });

  q.items1.push("hello"); // Fine
  q.items2.push({ key1: "123", key2: "why?" }); // Broken

  q.save(function() {
    // Fine...
    //Sub.findOne({}, function(err, q21) {
    //  q21.save(function() { console.log("OK"); });
    //});

    // Not fine...
    Base.findOne({}, function(err, q22) {
      q22.save(function() { console.log("nope"); });
    });
  });

});
});
```

As shown in the example, there is no problem with an item of type `[String]`, but there is with an item of type `[{ key1: String, key2: String }]`. I'm not sure why this is, but my guess is that this is occurring because the `Sub` instance isn't actually being created as a `Sub` instance, it's just a `Base` instance whose prototype is then changed, so the `items2` property isn't set up properly so its `validate` method doesn't exist.

**Comment by sieira** [comment] 2015-11-11 10:26
I couldn't reproduce the problem, it is working for me. I'm closing. Don't hesitate to reopen if you find this issue again

**Closed by sieira** 2015-11-11 10:26 UTC
